{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "87e37fb2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set libraries, working dir\n",
    "import os\n",
    "import pandas as pd\n",
    "import json\n",
    "import csv\n",
    "import numpy as np\n",
    "\n",
    "os.chdir(\"C:/Users/name/Desktop/SACR_detection\")\n",
    "os.getcwd()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dc21ef73",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Inputs: csv_file= input of csv with annotation data; export_json= name of COCO json to export\n",
    "csv_file = 'csv to coco template.csv'\n",
    "export_json = 'test123.json'\n",
    "\n",
    "# Inputs: link the name of classes related to its index\n",
    "categories = [{\"id\":1, \"name\": \"duck_goose\"},{\"id\":2, \"name\": \"sandhill crane\"}]\n",
    "\n",
    "# Inputs; please fill in image width and height below\n",
    "\n",
    "dtype = {'image_id': np.int64, 'label_id': np.int64}\n",
    "csv_data = pd.read_csv(csv_file, dtype=dtype) \n",
    "csv_data['image_id']= csv_data['image_id'].astype(int)\n",
    "csv_data.columns = (['id','image_id','unique_image_jpg','x_min', 'y_min', 'w','h','label','label_id','author',\n",
    "                     'bbname','unique_image_path'])\n",
    "csv_data['annid'] = csv_data.index\n",
    "\n",
    "# Create 3 major lists to fill in, including nested dictionaries\n",
    "#categories = []\n",
    "images = []\n",
    "annotations = []\n",
    "\n",
    "def image(row):\n",
    "    image = {}\n",
    "    # height and width of parent image\n",
    "    image[\"width\"] = 1280 ## custom for your imagery\n",
    "    image[\"height\"] = 720 ## custom for your imagery\n",
    "    image[\"id\"] = row.image_id\n",
    "    image[\"file_name\"] = row.unique_image_path\n",
    "  # image[\"observer\"] = row.author\n",
    "    return image\n",
    "\n",
    "def annotation(row):\n",
    "    annotation = {}\n",
    "    annotation[\"id\"] = row.id\n",
    "    annotation[\"image_id\"] = row.image_id\n",
    "    annotation[\"category_id\"] = row.label_id\n",
    "   # annotation[\"segmentation\"] = []\n",
    "    annotation[\"bbox\"] = [row.x_min, row.y_min, row.w, row.h]\n",
    "    annotation[\"ignore\"] = 0\n",
    "    annotation[\"iscrowd\"] = 0\n",
    "    annotation[\"area\"] = (row.h * row.w)\n",
    "    return annotation\n",
    "\n",
    "# Iterates through rows\n",
    "for index, row in csv_data.iterrows():\n",
    "    annotations.append(annotation(row))\n",
    "    images.append(image(row))   \n",
    "len(images)\n",
    "\n",
    "# remove duplicate images\n",
    "images2 = []\n",
    "\n",
    "imagedf = csv_data.drop_duplicates(subset=['image_id'])\n",
    "for index, row in imagedf.iterrows():\n",
    "    images2.append(image(row)) \n",
    "len(images2)\n",
    "\n",
    "data_coco = {}\n",
    "data_coco[\"images\"] = images2\n",
    "data_coco[\"categories\"] = categories\n",
    "data_coco[\"annotations\"] = annotations\n",
    "\n",
    "json.dump(data_coco, open(export_json,\"w\"), indent=0)\n",
    "print (\"Completed!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
